service: pickup-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev

useDotenv: true

functions:
  graphql:
    handler: src/index.handler
    name: graphql
    events:
      - http:
          path: /graphql
          method: POST
          cors: true
      - http:
          path: /graphql
          method: GET
          cors: true

  signinUser:
    handler: src/functions/auth/signinUser.signinUser
    name: signinUser
    events:
      - http:
          path: /signinUser
          method: POST
          cors: true
  getUsers:
    handler: src/functions/auth/getUsers.getUsers
    name: getUsers
    events:
      - http:
          path: /getUsers
          method: GET
          cors: true

  validateEmail:
    handler: src/functions/auth/validateEmail.validateEmail
    name: validateEmail
    events:
      - http:
          path: /validateEmail
          method: POST
          cors: true
plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
package:
  patterns:
    - "node_modules/.prisma/**"
    - "node_modules/@prisma/**"
    - "prisma/**"
