service: pickup-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev

useDotenv: true

functions:
  graphql:
    handler: src/index.handler
    name: graphql-serverless
    events:
      - http:
          path: /graphql
          method: POST
          cors: true
      - http:
          path: /graphql
          method: GET
          cors: true

  signinUser:
    handler: src/functions/auth/signinUser.signinUser
    name: signinUser
    events:
      - http:
          path: /signinUser
          method: POST
          cors: true
  getUsers:
    handler: src/functions/auth/getUsers.getUsers
    name: getUsers 
    events:
      - http:
          path: /getUsers
          method: GET 
          cors: true

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: true
  serverless-offline:
    httpPort: 4000
