service: pickup-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev

useDotenv: true

functions:
  graphql:
    handler: src/index.handler
    name: graphql-serverless
    events:
      - http:
          path: /graphql
          method: POST
      - http:
          path: /graphql
          method: GET

  signinUser:
    handler: src/functions/auth/loginUser.loginUser
    name: signinUser
    events:
      - http:
          path: /loginUser
          method: POST

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: true
  serverless-offline:
    httpPort: 4000
