service: pickup

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

useDotenv: true

functions:
  graphql:
    handler: src/index.handler
    name: graphql
    events:
      - http:
          path: /graphql
          method: POST
          cors: true
      - http:
          path: /graphql
          method: GET
          cors: true
  loginUser:
    handler: src/functions/auth/loginUser.loginUser
    name: loginUser
    events:
      - http:
          path: /loginUser
          method: POST
          cors: true

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: true
  serverless-offline:
    httpPort: 4000
